### ISSUE TITLE
unable to resolve  maven depedencies.

### ISSUE THREAD

**Issue by matesio** [PredixDev/winddata-timeseries-service#12]
[DEBUG]    com.ge.predix.solsvc:timeseries-bootstrap:jar:2.1.23:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.269 s
[INFO] Finished at: 2017-08-25T14:48:12+05:00
[INFO] Final Memory: 12M/228M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project winddata-timeseries-service: Could not resolve dependencies for project com.ge.predix.solsvc:winddata-timeseries-service:jar:2.0.26: Failure to find com.ge.predix.solsvc:timeseries-bootstrap:jar:2.1.23 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project winddata-timeseries-service: Could not resolve dependencies for project com.ge.predix.solsvc:winddata-timeseries-service:jar:2.0.26: Failure to find com.ge.predix.solsvc:timeseries-bootstrap:jar:2.1.23 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

**Comment by turnerth** [comment]
this is usually because the maven settings.xml fijle is not configured with a password to the predix artifactory repo.  Please go to the tutorial and check out that instruction.
