### ISSUE TITLE
when running app we are getting Failed to collect dependencies at com.ge.predix.solsvc:ext-model:jar:1.7.11

### ISSUE THREAD

**Issue by mamidishetti** [PredixDev/winddata-timeseries-service#2]
when running time series app we are getting Failed to collect dependencies at com.ge.predix.solsvc:ext-model:jar:1.7.11

please help me in fixing this issue

**Comment by gstroup** [comment]
Are you still seeing this problem?  In the cloud or locally?  I'm not seeing any issues.

**Comment by turnerth** [comment]
check the latest forum post 
https://forum.predix.io/questions/8767/when-running-winddata-timeseries-service-app-getti.html

**Comment by mamidishetti** [comment]
getting below error after changing repositry path

=============================================================================== [INFO] ------------------------------------------------------------- [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\com\ge\predix\solsvc\timese ies-bootstrap\1.2.13\timeseries-bootstrap-1.2.13.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\httpcomponents\h tpclient\4.5.2\httpclient-4.5.2.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\httpcomponents\h tpcore\4.4.4\httpcore-4.4.4.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\commons-codec\commons-codec 1.9\commons-codec-1.9.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\boot\sp ing-boot-starter-web\1.2.3.RELEASE\spring-boot-starter-web-1.2.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\boot\sp ing-boot-starter\1.2.3.RELEASE\spring-boot-starter-1.2.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\boot\sp ing-boot\1.2.3.RELEASE\spring-boot-1.2.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\boot\sp ing-boot-autoconfigure\1.2.3.RELEASE\spring-boot-autoconfigure-1.2.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\boot\sp ing-boot-starter-logging\1.2.3.RELEASE\spring-boot-starter-logging-1.2.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\slf4j\jcl-over-slf4j\1. .11\jcl-over-slf4j-1.7.11.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\slf4j\slf4j-api\1.7.11\ lf4j-api-1.7.11.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\slf4j\jul-to-slf4j\1.7. 1\jul-to-slf4j-1.7.11.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\slf4j\log4j-over-slf4j\ .7.11\log4j-over-slf4j-1.7.11.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\ch\qos\logback\logback-clas ic\1.1.3\logback-classic-1.1.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\ch\qos\logback\logback-core 1.1.3\logback-core-1.1.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\yaml\snakeyaml\1.14\sna eyaml-1.14.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\boot\sp ing-boot-starter-tomcat\1.2.3.RELEASE\spring-boot-starter-tomcat-1.2.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\tomcat\embed\tom at-embed-core\8.0.20\tomcat-embed-core-8.0.20.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\tomcat\embed\tom at-embed-el\8.0.20\tomcat-embed-el-8.0.20.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\tomcat\embed\tom at-embed-logging-juli\8.0.20\tomcat-embed-logging-juli-8.0.20.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\tomcat\embed\tom at-embed-websocket\8.0.20\tomcat-embed-websocket-8.0.20.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\com\fasterxml\jackson\core\ ackson-databind\2.4.5\jackson-databind-2.4.5.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\com\fasterxml\jackson\core\ ackson-annotations\2.4.5\jackson-annotations-2.4.5.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\com\fasterxml\jackson\core\ ackson-core\2.4.5\jackson-core-2.4.5.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\hibernate\hibernate-val dator\5.1.3.Final\hibernate-validator-5.1.3.Final.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\javax\validation\validation api\1.1.0.Final\validation-api-1.1.0.Final.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\jboss\logging\jboss-log ing\3.1.3.GA\jboss-logging-3.1.3.GA.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\com\fasterxml\classmate\1.0 0\classmate-1.0.0.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\spring- ore\4.1.6.RELEASE\spring-core-4.1.6.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\spring- eb\4.1.6.RELEASE\spring-web-4.1.6.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\spring- ebmvc\4.1.6.RELEASE\spring-webmvc-4.1.6.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\cloud\s ring-cloud-core\1.1.1.RELEASE\spring-cloud-core-1.1.1.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\cxf\cxf-rt-front nd-jaxrs\2.7.3\cxf-rt-frontend-jaxrs-2.7.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\cxf\cxf-api\2.7. \cxf-api-2.7.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\ws\xmlschema\xml chema-core\2.0.3\xmlschema-core-2.0.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\geronimo\specs\g ronimo-javamail_1.4_spec\1.7.1\geronimo-javamail_1.4_spec-1.7.1.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\wsdl4j\wsdl4j\1.6.3\wsdl4j- .6.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\cxf\cxf-rt-core\ .7.3\cxf-rt-core-2.7.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\com\sun\xml\bind\jaxb-impl\ .1.13\jaxb-impl-2.1.13.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\javax\ws\rs\javax.ws.rs-api 2.0-m10\javax.ws.rs-api-2.0-m10.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\cxf\cxf-rt-bindi gs-xml\2.7.3\cxf-rt-bindings-xml-2.7.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\cxf\cxf-rt-trans orts-http\2.7.3\cxf-rt-transports-http-2.7.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\cxf\cxf-rt-rs-ex ension-providers\2.7.3\cxf-rt-rs-extension-providers-2.7.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\codehaus\jackson\jackso -jaxrs\1.9.2\jackson-jaxrs-1.9.2.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\codehaus\jackson\jackso -core-asl\1.9.2\jackson-core-asl-1.9.2.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\codehaus\jackson\jackso -mapper-asl\1.9.2\jackson-mapper-asl-1.9.2.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\boot\sp ing-boot-starter-security\1.2.3.RELEASE\spring-boot-starter-security-1.2.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\spring- eans\4.1.6.RELEASE\spring-beans-4.1.6.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\spring- ontext\4.1.6.RELEASE\spring-context-4.1.6.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\spring- xpression\4.1.6.RELEASE\spring-expression-4.1.6.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\securit \spring-security-config\3.2.7.RELEASE\spring-security-config-3.2.7.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\aopalliance\aopalliance\1.0 aopalliance-1.0.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\securit \spring-security-web\3.2.7.RELEASE\spring-security-web-3.2.7.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\spring- op\4.1.6.RELEASE\spring-aop-4.1.6.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\securit \oauth\spring-security-oauth2\2.0.3.RELEASE\spring-security-oauth2-2.0.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\securit \spring-security-core\3.2.7.RELEASE\spring-security-core-3.2.7.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\mockito\mockito-all\1.9 5\mockito-all-1.9.5.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\kubek2k\springockito\1. .9\springockito-1.0.9.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\com\ge\predix\solsvc\ext-mo el\1.7.11\ext-model-1.7.11.jar; error in opening zip file [INFO] 59 errors [INFO] ------------------------------------------------------------- [INFO] ------------------------------------------------------------------------ [INFO] BUILD FAILURE [INFO] ------------------------------------------------------------------------ [INFO] Total time: 4.992 s [INFO] Finished at: 2016-07-07T17:52:58+05:30 [INFO] Final Memory: 16M/213M [INFO] ------------------------------------------------------------------------ [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.1:compile (default-compile) on project winddata-timeserie -service: Compilation failure: Compilation failure: [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\com\ge\predix\solsvc\timese ies-bootstrap\1.2.13\timeseries-bootstrap-1.2.13.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\httpcomponents\h tpclient\4.5.2\httpclient-4.5.2.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\httpcomponents\h tpcore\4.4.4\httpcore-4.4.4.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\commons-codec\commons-codec 1.9\commons-codec-1.9.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\boot\sp ing-boot-starter-web\1.2.3.RELEASE\spring-boot-starter-web-1.2.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\boot\sp ing-boot-starter\1.2.3.RELEASE\spring-boot-starter-1.2.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\boot\sp ing-boot\1.2.3.RELEASE\spring-boot-1.2.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\boot\sp ing-boot-autoconfigure\1.2.3.RELEASE\spring-boot-autoconfigure-1.2.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\boot\sp ing-boot-starter-logging\1.2.3.RELEASE\spring-boot-starter-logging-1.2.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\slf4j\jcl-over-slf4j\1. .11\jcl-over-slf4j-1.7.11.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\slf4j\slf4j-api\1.7.11\ lf4j-api-1.7.11.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\slf4j\jul-to-slf4j\1.7. 1\jul-to-slf4j-1.7.11.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\slf4j\log4j-over-slf4j\ .7.11\log4j-over-slf4j-1.7.11.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\ch\qos\logback\logback-clas ic\1.1.3\logback-classic-1.1.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\ch\qos\logback\logback-core 1.1.3\logback-core-1.1.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\yaml\snakeyaml\1.14\sna eyaml-1.14.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\boot\sp ing-boot-starter-tomcat\1.2.3.RELEASE\spring-boot-starter-tomcat-1.2.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\tomcat\embed\tom at-embed-core\8.0.20\tomcat-embed-core-8.0.20.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\tomcat\embed\tom at-embed-el\8.0.20\tomcat-embed-el-8.0.20.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\tomcat\embed\tom at-embed-logging-juli\8.0.20\tomcat-embed-logging-juli-8.0.20.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\tomcat\embed\tom at-embed-websocket\8.0.20\tomcat-embed-websocket-8.0.20.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\com\fasterxml\jackson\core\ ackson-databind\2.4.5\jackson-databind-2.4.5.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\com\fasterxml\jackson\core\ ackson-annotations\2.4.5\jackson-annotations-2.4.5.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\com\fasterxml\jackson\core\ ackson-core\2.4.5\jackson-core-2.4.5.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\hibernate\hibernate-val dator\5.1.3.Final\hibernate-validator-5.1.3.Final.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\javax\validation\validation api\1.1.0.Final\validation-api-1.1.0.Final.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\jboss\logging\jboss-log ing\3.1.3.GA\jboss-logging-3.1.3.GA.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\com\fasterxml\classmate\1.0 0\classmate-1.0.0.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\spring- ore\4.1.6.RELEASE\spring-core-4.1.6.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\spring- eb\4.1.6.RELEASE\spring-web-4.1.6.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\spring- ebmvc\4.1.6.RELEASE\spring-webmvc-4.1.6.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\cloud\s ring-cloud-core\1.1.1.RELEASE\spring-cloud-core-1.1.1.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\cxf\cxf-rt-front nd-jaxrs\2.7.3\cxf-rt-frontend-jaxrs-2.7.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\cxf\cxf-api\2.7. \cxf-api-2.7.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\ws\xmlschema\xml chema-core\2.0.3\xmlschema-core-2.0.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\geronimo\specs\g ronimo-javamail_1.4_spec\1.7.1\geronimo-javamail_1.4_spec-1.7.1.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\wsdl4j\wsdl4j\1.6.3\wsdl4j- .6.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\cxf\cxf-rt-core\ .7.3\cxf-rt-core-2.7.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\com\sun\xml\bind\jaxb-impl\ .1.13\jaxb-impl-2.1.13.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\javax\ws\rs\javax.ws.rs-api 2.0-m10\javax.ws.rs-api-2.0-m10.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\cxf\cxf-rt-bindi gs-xml\2.7.3\cxf-rt-bindings-xml-2.7.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\cxf\cxf-rt-trans orts-http\2.7.3\cxf-rt-transports-http-2.7.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\apache\cxf\cxf-rt-rs-ex ension-providers\2.7.3\cxf-rt-rs-extension-providers-2.7.3.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\codehaus\jackson\jackso -jaxrs\1.9.2\jackson-jaxrs-1.9.2.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\codehaus\jackson\jackso -core-asl\1.9.2\jackson-core-asl-1.9.2.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\codehaus\jackson\jackso -mapper-asl\1.9.2\jackson-mapper-asl-1.9.2.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\boot\sp ing-boot-starter-security\1.2.3.RELEASE\spring-boot-starter-security-1.2.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\spring- eans\4.1.6.RELEASE\spring-beans-4.1.6.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\spring- ontext\4.1.6.RELEASE\spring-context-4.1.6.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\spring- xpression\4.1.6.RELEASE\spring-expression-4.1.6.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\securit \spring-security-config\3.2.7.RELEASE\spring-security-config-3.2.7.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\aopalliance\aopalliance\1.0 aopalliance-1.0.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\securit \spring-security-web\3.2.7.RELEASE\spring-security-web-3.2.7.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\spring- op\4.1.6.RELEASE\spring-aop-4.1.6.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\securit \oauth\spring-security-oauth2\2.0.3.RELEASE\spring-security-oauth2-2.0.3.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\springframework\securit \spring-security-core\3.2.7.RELEASE\spring-security-core-3.2.7.RELEASE.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\mockito\mockito-all\1.9 5\mockito-all-1.9.5.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\org\kubek2k\springockito\1. .9\springockito-1.0.9.jar; error in opening zip file [ERROR] error: error reading D:\GEGDC\MD98012\Installations\apache-maven-3.3.9-bin\apache-maven-3.3.9\repositry\com\ge\predix\solsvc\ext-mo el\1.7.11\ext-model-1.7.11.jar; error in opening zip file [ERROR] -> [Help 1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug logging. [ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException =====================================================================================================================================================
