### ISSUE TITLE
ependencies com.ge.predix:uaa-token-lib:jar:2.0.0

### ISSUE THREAD

**Issue by AllanGottigNovotek** [PredixDev/winddata-timeseries-service#5]
Hi 

I get an error running:
[package clean error.txt](https://github.com/PredixDev/winddata-timeseries-service/files/500359/package.clean.error.txt)

[predix@predix-devbox ~]$ mvn clean package

It looks like I missing some permissions to the com.ge.predix:uaa-token-lib:jar:2.0.0 repository.
I can download it manually.
Please see the attached log.

My $ .m2/settings.xml is set. 
[predix@predix-devbox ~]$ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /usr/local/maven
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.el7_2.x86_64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-327.28.3.el7.x86_64", arch: "amd64", family: "unix"

I use the devBox 3.5.1

Best regards
Allan

**Comment by turnerth** [comment]
check out the tutorials on predix.io.  you'll see there is a maven setup you have to do.  The predix artifactory is password protected.
