### ISSUE TITLE
mvn clean package Build Failure

### ISSUE THREAD

**Issue by javiisanchez** [PredixDev/winddata-timeseries-service#7]
I'm doing the tutorial, but when  I'm doing the comand:  mvn package clean,
The result is:

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building winddata-timeseries-service 2.0.4
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.ge.predix:uaa-token-lib:jar:2.0.0 is missing, no dependency information available
[WARNING] The POM for com.ge.predix:acs-spring-security-extensions:jar:5.1.0 is missing, no dependency information available
[WARNING] The POM for com.ge.predix.solsvc:ext-model:jar:2.0.4 is missing, no dependency information available
[WARNING] The POM for com.ge.predix.solsvc:timeseries-bootstrap:jar:2.1.2 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.487 s
[INFO] Finished at: 2016-10-27T11:29:31+02:00
[INFO] Final Memory: 11M/115M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project winddata-timeseries-service: Could not resolve dependencies for project com.ge.predix.solsvc:winddata-timeseries-service:jar:2.0.4: The following artifacts could not be resolved: com.ge.predix:uaa-token-lib:jar:2.0.0, com.ge.predix:acs-spring-security-extensions:jar:5.1.0, com.ge.predix.solsvc:ext-model:jar:2.0.4, com.ge.predix.solsvc:timeseries-bootstrap:jar:2.1.2: Cannot access central (https://repo.maven.apache.org/maven2) in offline mode and the artifact com.ge.predix:uaa-token-lib:jar:2.0.0 has not been downloaded from it before. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

My pomp.xml hava a dependency:
<dependency>
   <groupId>com.ge.predix.solsvc</groupId>
    <artifactId>timeseries-bootstrap</artifactId>
    <version>${predix-timeseries-client.version}</version>
</dependency>

And my <user directory>.m2/settings contain the server configuration:
<server>
      <id>artifactory.external</id>
      <username>j.sanchez.buitrago@accenture.com</username>
      <password>AP3tEAbrVzENViKF9wT7nGFTcX9</password>
      <filePermissions>664</filePermissions>
      <directoryPermissions>775</directoryPermissions>
      <configuration></configuration>
    </server>

Iqual to my settings.xml in <maven install>/conf/settings

My VCAP is the following:
"VCAP_SERVICES": {
  "predix-timeseries": [
   {
    "credentials": {
     "ingest": {
      "uri": "wss://gateway-predix-data-services.run.aws-usw02-pr.ice.predix.io/v1/stream/messages",
      "zone-http-header-name": "Predix-Zone-Id",
      "zone-http-header-value": "857dce62-f007-4ea6-a8f5-10dcd2172e8e",
      "zone-token-scopes": [
       "timeseries.zones.857dce62-f007-4ea6-a8f5-10dcd2172e8e.user",
       "timeseries.zones.857dce62-f007-4ea6-a8f5-10dcd2172e8e.ingest"
      ]
     },
     "query": {
      "uri": "https://time-series-store-predix.run.aws-usw02-pr.ice.predix.io/v1/datapoints",
      "zone-http-header-name": "Predix-Zone-Id",
      "zone-http-header-value": "857dce62-f007-4ea6-a8f5-10dcd2172e8e",
      "zone-token-scopes": [
       "timeseries.zones.857dce62-f007-4ea6-a8f5-10dcd2172e8e.user",
       "timeseries.zones.857dce62-f007-4ea6-a8f5-10dcd2172e8e.query"
      ]

My config/application-external.properties also have was modified:

logging.level.org.apache.http.impl.client=DEBUG
server.port=9092
spring.profiles.active=local
predix.oauth.grantType=client_credentials
# if you are behind a corporate proxy/firewall and want to access Predix Cloud
# predix.oauth.proxyHost =put.your.proxyHost.here
# predix.oauth.proxyPort=put.your.proxyPort.here
# OAuth - please see predix-rest-client src/main/java/com/ge/predix/solsvc/restclient/config/OauthRestConfig.java for more info on oauth properties

predix.oauth.restHost=https://0e09ac0a-1b28-4d8a-b4d4-320a9843d4f2.predix-uaa.run.aws-usw02-pr.ice.predix.io
# you may put client:secret as unencoded cleartext by setting predix.oauth.clientIdEncode=true

predix.oauth.clientIdEncode=false
predix.oauth.clientId=app_client_id:Accenture1 
# timeseries - get from VCAP env vars by binding an application to your timeseries instance e.g. cf bind-service <my-app> <my-timeseries>
# timeseries - see timeseries-bootstrap - src/main/java/com/ge/predix/solsvc/timeseries/bootstrap/config/TimeseriesRestConfig.java for more info on timeseries properties

predix.timeseries.ingestUri=wss://gateway-predix-data-services.run.aws-usw02-pr.ice.predix.io/v1/stream/messages
predix.timeseries.baseUrl=https://time-series-store-predix.run.aws-usw02-pr.ice.predix.io/v1/datapoints
predix.timeseries.websocket.connection.retry=1
predix.timeseries.zoneid=857dce62-f007-4ea6-a8f5-10dcd2172e8e
# deprecated - these override variables we are refactoring away from.

predix.timeseries.override.oauthOverride=false
predix.timeseries.override.oauthClientId=app_client_id:Accenture1
predix.timeseries.override.oauthRestHost=https://0e09ac0a-1b28-4d8a-b4d4-320a9843d4f2.predix-uaa.run.aws-usw02-pr.ice.predix.io
predix.websocket.pool.maxActive=5 
predix.websocket.pool.maxWait=8000 
predix.websocket.pool.maxInstances=5

I don't know, how resolve the dependencies of the problem.
If you can help me please, just let me know!

**Comment by turnerth** [comment]
Ensure you have set up your predix.io username/encrypted password in the maven settings.xml. Instruction are found here.

https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=1560&tag=1608&journey=Development%20tools%20and%20tips&resources=1565,1560
