### ISSUE TITLE
Problem when I'm doing the app locally (winddattaservice)

### ISSUE THREAD

**Issue by javiisanchez** [PredixDev/winddata-timeseries-service#8]
Hi, I'm doing the tutorial about winddata-timeseries-service. https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=1553&tag=Time%20Series&journey=Time%20Series After I did the comand mvn spring-boot:run, to doing the app locally, the initialization completed. But when I open the http://localhost:9092/services/windservices/yearly_data/sensor_id/Compressor-2015:CompressionRatio: I see the following: Whitelabel Error Page This application has no explicit mapping for /error, so you are seeing this as a fallback. Mon Oct 31 13:21:00 CET 2016 There was an unexpected error (type=Internal Server Error, status=500). org.apache.cxf.interceptor.Fault: Query was unsuccessful. Status Code:404 Response Body= I don't understandnt the reason. The same away when I'm doing the push to see the app in the cloud, and when I enter to: https://predixdemopredix-microservice-cf-jsr.run.aws-usw02-pr.ice.predix.io/services/windservices/yearly_data/sensor_id/Compressor-2015:CompressionRatio I see the following: {"status":404,"error":"Not Found","message":"No message available","timeStamp":"Mon Oct 31 12:23:28 UTC 2016"} I think that the error is relationed. Attach my manifest and application.propeties and my VCAP variables. If it help you when I'm installing the timeseris bootstrap (mvn clean install) and it's doing the test, it produce 2 errors are: Tests in error: runIDataInjectionTest(com.ge.predix.solsvc.timeseries.bootstrap.factories.TimeseriesFactoryIT): Query was unsuccessful. Status Code:404 Response Body= runAllTest(com.ge.predix.solsvc.timeseries.bootstrap.factories.TimeseriesFactoryIT): Query was unsuccessful. Status Code:404 Response Body= Seems that are relattioned. Thanks!!!

**Comment by turnerth** [comment]
the IT tests require that you set up config/application.properties.  Did you set all those values? Also, when you run locally it uses those same values.

When you run in the cloud it requires the manifest.yml to be configured properly.

I would suggest you run it locally from Eclipse and use the debugger, put a breakpoint in there.  Then you can see what properties are misconfigured.

Please refresh the tutorial also do a git pull, we made some better comments in the prop file this morning.

**Comment by javiisanchez** [comment]
Yes, I set up the config/application.properties, if I wouldn't do it correctly, the mave clean install, the local wouldn't be build.

my file is the following:
#properties for running locally or for unit tests

#logging.level.root=DEBUG
logging.level.org.springframework=INFO
logging.level.com.ge.predix.solsvc=DEBUG
logging.level.org.apache.http.impl.client=DEBUG
server.port=9092
spring.profiles.active=local
predix.oauth.grantType=client_credentials

#if you are behind a corporate proxy/firewall and want to access Predix Cloud
#predix.oauth.proxyHost =put.your.proxyHost.here
#predix.oauth.proxyPort=put.your.proxyPort.here

#OAuth - please see predix-rest-client src/main/java/com/ge/predix/solsvc/restclient/config/OauthRestConfig.java for more info on oauth properties
predix.oauth.restHost=0e09ac0a-1b28-4d8a-b4d4-320a9843d4f2.predix-uaa.run.aws-usw02-pr.ice.predix.io
#you may put client:secret as unencoded cleartext by setting predix.oauth.clientIdEncode=true
predix.oauth.clientIdEncode=false
predix.oauth.clientId=YXBwX2NsaWVudF9pZDpBY2NlbnR1cmUx

#timeseries - get from VCAP env vars by binding an application to your timeseries instance e.g. cf bind-service <my-app> <my-timeseries>
#timeseries - see timeseries-bootstrap - src/main/java/com/ge/predix/solsvc/timeseries/bootstrap/config/TimeseriesRestConfig.java for more info on timeseries properties 
predix.timeseries.ingestUri=wss://gateway-predix-data-services.run.aws-usw02-pr.ice.predix.io/v1/stream/messages
predix.timeseries.baseUrl=https://time-series-store-predix.run.aws-usw02-pr.ice.predix.io/v1/datapoints
predix.timeseries.websocket.connection.retry=1
predix.timeseries.zoneid=857dce62-f007-4ea6-a8f5-10dcd2172e8e
#deprecated - these override variables we are refactoring away from. 
predix.timeseries.override.oauthOverride=false
predix.timeseries.override.oauthClientId=YXBwX2NsaWVudF9pZDpBY2NlbnR1cmUx
predix.timeseries.override.oauthRestHost=0e09ac0a-1b28-4d8a-b4d4-320a9843d4f2.predix-uaa.run.aws-usw02-pr.ice.predix.io
predix.websocket.pool.maxIdle=5
predix.websocket.pool.maxActive=5 
predix.websocket.pool.maxWait=8000 
predix.websocket.pool.maxInstances=5

And for run in to the cloud use the following configurations in the manifest:
#inherit: base-manifest.yml
applications:
- name: Wind-timeseries-service
  buildpack: java_buildpack
  path: target/winddata-timeseries-service-2.0.4.jar
  memory: 256M
  services:
  - Test
  - TimeSeries-Service
    env:
    node_env: cloud
    uaa_service_label : predix-uaa
    clientId: app_client_id
    base64ClientCredential: YXBwX2NsaWVudF9pZDpBY2NlbnR1cmUx
  
  predix_timeseries_name : TimeSeries-Service
  predix_oauthRestHost : 0e09ac0a-1b28-4d8a-b4d4-320a9843d4f2.predix-uaa.run.aws-usw02-pr.ice.predix.io
  predix_oauthClientId : app_client_id:Accenture1
  trustedIssuerIdsRegexPattern : ^http://(.*\.)?.predix-uaa.run.aws-usw02-pr.ice/oauth/token$
  predix_connectionTimeout : 5000
  predix_socketTimeout : 5000
  
  accessTokenEndpointUrl : https://0e09ac0a-1b28-4d8a-b4d4-320a9843d4f2.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token
  clientId : app_user_1
  clientSecret: app_user_1
  predix_poolMaxSize: 200
  defaultMaxPerRoute: 25
  predix_wspool_maxIdle : 5
  predix_wspool_maxActive : 5
  predix_wspool_maxWait : 8000
  predix_wspool_maxInstances : 5

**Comment by turnerth** [comment]
Please change
predix.timeseries.baseUrl=https://time-series-store-predix.run.aws-usw02-pr.ice.predix.io/v1/datapoints

to

predix.timeseries.baseUrl=https://time-series-store-predix.run.aws-usw02-pr.ice.predix.io

That was the tutorial and template change we made clearer this morning.

**Comment by javiisanchez** [comment]
The result in the (http://localhost:9092/services/windservices/yearly_data/sensor_id/Compressor-2015:CompressionRatio) continue with the same error:

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Nov 03 09:21:34 CET 2016
There was an unexpected error (type=Internal Server Error, status=500).
org.apache.cxf.interceptor.Fault: javax/ws/rs/MessageProcessingException

What are the reasons that you believe that produced this error?

**Comment by javiisanchez** [comment]
If I open the front-end locally in http://localhost:3000 I see the data who the tutorial show in the graphic.

**Comment by turnerth** [comment]
let's just work off the forum thread...i'm getting confused what has been answered.  no more comments here please.
