### ISSUE TITLE
manifest.yml: Properties are not supported

### ISSUE THREAD

**Issue by sebastianroming** [PredixDev/winddata-timeseries-service#9]
When trying to push the example to cf, i get the following error message:

```
FAILED
Error reading manifest file:
Property '${timeSeriesService}' found in manifest. This feature is no longer supported. Please remove it and try again.
```

**Comment by turnerth** [comment]
please read the tutorial closely.  you need to put the name of the timeseries service in that property

It says....
Go to manifest.yml and change services with the names of the service instances you created in Exploring Application Security: Create a Predix Service and set up UAA ClientId.

services:
      - <your-name>-secure-uaa-instance
      - <your-name>-timeseries-instance
